### ISSUE TITLE
Create docker image & refactor code

### ISSUE THREAD

**Issue by ToshY** [ToshY/pexels-scraper#1]
While I currently don't use this repo myself anymore, I feel the need to refactor the code and modernise it by also creating a docker image for it. If I keep the existing input arguments the same there won't be any breaking changes.

**Comment by franciscomurciagomez** [comment]
What is the name of the dockerimage of dockerhub?

**Comment by ToshY** [comment]
Hey @franciscomurciagomez 👋 

The point of this issue is that I still want to create a docker image for this 🙂 

It should not be _that_ much work, but I didn't have much time last week. 

If you are interested, I can take a look at it later today and probably create and publish the first image by tonight.

**Comment by ToshY** [comment]
@franciscomurciagomez 

> What is the name of the dockerimage of dockerhub?

[t0shy/pexels-scraper](https://hub.docker.com/r/t0shy/pexels-scraper). 

See the [README ](https://github.com/ToshY/pexels-scraper/blob/master/README.md) on how-to-use.
